### ISSUE TITLE
Change configuration format to YAML

### ISSUE THREAD

**Issue by pacoorozco** [gphotosuploader/gphotos-uploader-cli#201]
**Is your feature request related to a problem? Please describe.**
No, it's not related to a problem, but I think YAML is more suitable for configuration. It's easier to read than JSON.

**Describe the solution you'd like**
The approach is to change the default configuration file to YAML format. This should be backwards compatible, so by using a flag or by detecting JSON format we should translate it to YAML.

**Describe alternatives you've considered**
Adding a flag to use YAML or JSON format for configuration

**Additional context**

This is an example of the configuration:
```
--- 
Credentials: 
  APIAppCredentials: 
    ClientID: XXXXXX
    ClientSecret: XXXXXX
  SecretsBackendType: auto
Defaults: 
  - 
    account: yourEmail@gmail.com
    deleteAfterUpload: false
    filters: 
      exclude: 
        - "**/ScreenShot*"
      include: 
        - "**/*.png"
        - "**/*.jpg"
Jobs: 
  -
    name: JobWithDefaults
    SourceFolder: "~/myPictures"
  - 
    name: JobWithOverrides
    SourceFolder: "~/myAwesomePictures"
    account: yourAlternativeEmail@gmail.com
    deleteAfterUpload: true
    filters: # Leave it empty to not use defaults
    makeAlbums: 
      enabled: false    
```
